# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
# Full ref https://circleci.com/docs/2.0/configuration-reference/
#
version: 2

jobs:
  build:
    docker:
      # Android the primary container
      - image: circleci/android:api-26-alpha
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/code

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
#      KEYSTORE: ${HOME}/repo/signing.keystore
    
    steps:
      - checkout

      - run: echo 'export KEYSTORE=${HOME}/code/signing.keystore' >> $BASH_ENV

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run: 
          name: Read key file
          command: ./.circleci/download_keystore.sh

      - run:
          name: Run build
          command: ./gradlew clean build

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Run UnitTest
          command: ./gradlew testDebugUnitTest

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-19;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-19;default;armeabi-v7a"

      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -no-audio -no-boot-anim -no-window -accel on -no-snapshot-save -camera-back none -verbose
          background: true

      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82

      - run:
          name: Run EspressoTests
          command: ./gradlew connectedDebugAndroidTest

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results

          